# Generated by Django 5.0.6 on 2024-05-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='processed',
            new_name='approved',
        ),
    ]
