# Generated by Django 5.0.6 on 2024-05-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_component_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='datasheet_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
