# Generated by Django 5.0.6 on 2024-05-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_processed_request_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='use',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
