# Generated by Django 5.0.6 on 2024-05-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_request_quantity_use_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
