# Generated by Django 5.0.6 on 2024-06-01 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_request_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.component'),
        ),
        migrations.AlterField(
            model_name='use',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profile'),
        ),
    ]
