# Generated by Django 5.0.6 on 2024-06-01 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_use_component_alter_use_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.component'),
        ),
        migrations.AlterField(
            model_name='use',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
