# Generated by Django 5.0.6 on 2024-06-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_use_component_alter_use_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
