# Generated by Django 5.0.6 on 2024-06-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_request_viewed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('row', 'column', 'depth'), name='unique_location'),
        ),
    ]
